import React from 'react';

import { Inter } from 'next/font/google';

import { ApolloWrapper } from '@/lib/ApolloWrapper.client';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// NOTE: 一律でキャッシュ期間を1秒に設定しています。特定のリクエストでは長く保持したい等あればfetch時に指定することで変更できます。
export const revalidate = 1;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
